notifications:
  email:
    recipients: "my@box.com"
    on_start: "never"
    on_failure: "always"
    on_success: "always"
#Build configuration
build:
  projectFolder: 'project'
  buildCommand: "pwd"
  #buildCommand: "mvn clean test"

#Database configuration
database:
  databaseFolder: 'database'
  databaseCommand: "mvn clean test -Dscope=FlywayMigration"
#Deploy configuration
deploy:
  deployCommand: "ls"
  #deployCommand: "mvn clean install"

#Test configuration (should be run in parallel)
test:
- testFolder: "test"
  name: "performance"
  testCommand: "mvn clean test -Dscope=performance"
- testFolder: "test"
  name: "regression"
  testCommand: "mvn clean test -Dscope=regression; exit 1"
- testFolder: "test"
  name: "integration"
  testCommand: "mvn clean test -Dscope=integration"